# Generated by Django 5.0.2 on 2024-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.TextField()),
                ('pic', models.ImageField(upload_to='media/')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
