# Generated by Django 5.0.2 on 2024-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='employee',
    #         name='pic',
    #         field=models.ImageField(upload_to='upload/'),
    #     ),
    # ]
