# Generated by Django 5.0.2 on 2024-02-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_employee_pic'),
    ]

    operations = [
    ]
