# Generated by Django 5.0.2 on 2024-02-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240215_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
